---
- hosts: awx
  gather_facts: true
  become: true
  become_method: sudo

  vars:
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py

  vars_files:
    - secrets/awx/vault.yml

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - roles/awx-install
