---

- hosts: jenkins
  gather_facts: true
  become: true
  become_method: sudo

  vars:
    - jenkins_package_state: latest
    - jenkins_hostname: jenkins.int.systemiphus.com
    - python_release: 3.7.1
    - python_install_dir: /usr
    - git_install_from_source: true
    - git_install_from_source_force_update: true
    - git_install_path: "/usr"
    - git_version: "2.20.1"

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.git
    - nmusatti.source_python
    - geerlingguy.docker