---

- hosts: jenkins
  gather_facts: true
  become: true
  become_method: sudo

  vars:
    - jenkins_package_state: latest
    - jenkins_hostname: jenkins.int.systemiphus.com
    - jenkins_http_port: 80

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
