---

- hosts: all
  gather_facts: yes
  become: true
  become_method: sudo
  
  vars_files:
    # roles/users
    - secrets/all/vault.yml
  
  vars:
    # roles/base
    apt_packages:
      - python3-pip
    python_packages: 
      - passlib
    # debops.fail2ban
    fail2ban_jails:
      - name: 'ssh'
        enabled: true
        comment: "This is to lock out SSH"
    # Python install
    python_versions: [2.7, 3.6]

  roles:
    - roles/base
    - roles/users
    - debops.fail2ban
    - Stouts.python
  
  tasks:
    - name: "Install AWS CLI through pip"
      become: true
      become_method: sudo
      pip:
        name: awscli